"""initial lab schema

Revision ID: 3f8783a7d3b1
Revises: 
Create Date: 2026-09-28 16:30:56.308064
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3f8783a7d3b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_device_id'), 'commands', ['device_id'], unique=False)
    op.create_index(op.f('ix_commands_request_id'), 'commands', ['request_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('remote', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_device_id'), 'connections', ['device_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('android_version', sa.String(length=16), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('payloads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('message_type', sa.String(length=24), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payloads_device_id'), 'payloads', ['device_id'], unique=False)
    op.create_index(op.f('ix_payloads_request_id'), 'payloads', ['request_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_device_id'), 'permissions', ['device_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_device_id'), 'security_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_security_events_rule_id'), 'security_events', ['rule_id'], unique=False)
    op.create_index('ix_security_events_rule_severity', 'security_events', ['rule_id', 'severity'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_pk', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_device_id'), 'events', ['device_id'], unique=False)
    op.create_index(op.f('ix_events_device_pk'), 'events', ['device_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_device_pk'), table_name='events')
    op.drop_index(op.f('ix_events_device_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index('ix_security_events_rule_severity', table_name='security_events')
    op.drop_index(op.f('ix_security_events_rule_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_device_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_permissions_device_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_payloads_request_id'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_device_id'), table_name='payloads')
    op.drop_table('payloads')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_connections_device_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_commands_request_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_device_id'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
